[workspace]
authors = ["Mahesh Binzer-Panchal <mahesh.binzer-panchal@nbis.se>"]
channels = ["conda-forge", "bioconda"]
name = "nf-metaomics-daisychain"
platforms = ["linux-64", "osx-arm64"]
version = "0.1.0"

[tasks]
chain = "nextflow run main.nf -params-file meta-pipeline-params.yml"

[dependencies]
nextflow = ">=26.04.6,<27"
nf-core = ">=3.2.0,<4"
quarto = ">=1.6.42,<2"
nf-test = ">=0.9.5,<1"
